"""add scheduled scan settings to cloud accounts

Revision ID: 4841b81d124e
Revises: 4661d3e99224
Create Date: 2025-10-06 13:34:30.607311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4841b81d124e'
down_revision: Union[str, None] = '4661d3e99224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_accounts', sa.Column('scheduled_scan_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('cloud_accounts', sa.Column('scheduled_scan_frequency', sa.String(length=20), nullable=False, server_default='daily'))
    op.add_column('cloud_accounts', sa.Column('scheduled_scan_hour', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('cloud_accounts', sa.Column('scheduled_scan_day_of_week', sa.Integer(), nullable=True))
    op.add_column('cloud_accounts', sa.Column('scheduled_scan_day_of_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_accounts', 'scheduled_scan_day_of_month')
    op.drop_column('cloud_accounts', 'scheduled_scan_day_of_week')
    op.drop_column('cloud_accounts', 'scheduled_scan_hour')
    op.drop_column('cloud_accounts', 'scheduled_scan_frequency')
    op.drop_column('cloud_accounts', 'scheduled_scan_enabled')
    # ### end Alembic commands ###
