"""add pricing_cache table

Revision ID: 4e275083c57b
Revises: 509cd9b0ecb0
Create Date: 2025-11-01 11:29:40.494732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e275083c57b'
down_revision: Union[str, None] = '509cd9b0ecb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='Cloud provider: aws, azure, gcp'),
    sa.Column('service', sa.String(length=100), nullable=False, comment='Service or SKU identifier (e.g., ebs_gp3, Standard_LRS)'),
    sa.Column('region', sa.String(length=50), nullable=False, comment='Cloud region (e.g., us-east-1, eastus, us-central1)'),
    sa.Column('price_per_unit', sa.Float(), nullable=False, comment='Price per unit (e.g., $/GB/month, $/hour)'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Unit of measurement (e.g., GB, hour, request)'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency code (USD)'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Source of pricing (api, fallback, manual)'),
    sa.Column('api_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Original API response metadata (for debugging)'),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when price was last updated'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Expiration timestamp (24h TTL)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_cache_expires_at', 'pricing_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pricing_cache_id'), 'pricing_cache', ['id'], unique=False)
    op.create_index('ix_pricing_cache_lookup', 'pricing_cache', ['provider', 'service', 'region'], unique=True)
    op.create_index(op.f('ix_pricing_cache_provider'), 'pricing_cache', ['provider'], unique=False)
    op.create_index(op.f('ix_pricing_cache_region'), 'pricing_cache', ['region'], unique=False)
    op.create_index(op.f('ix_pricing_cache_service'), 'pricing_cache', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_cache_service'), table_name='pricing_cache')
    op.drop_index(op.f('ix_pricing_cache_region'), table_name='pricing_cache')
    op.drop_index(op.f('ix_pricing_cache_provider'), table_name='pricing_cache')
    op.drop_index('ix_pricing_cache_lookup', table_name='pricing_cache')
    op.drop_index(op.f('ix_pricing_cache_id'), table_name='pricing_cache')
    op.drop_index('ix_pricing_cache_expires_at', table_name='pricing_cache')
    op.drop_table('pricing_cache')
    # ### end Alembic commands ###
