"""create_scans_and_orphan_resources_tables

Revision ID: 92aa66830ad2
Revises: ea68df898a6b
Create Date: 2025-10-02 13:37:04.688949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92aa66830ad2'
down_revision: Union[str, None] = 'ea68df898a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cloud_account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('total_resources_scanned', sa.Integer(), nullable=False),
    sa.Column('orphan_resources_found', sa.Integer(), nullable=False),
    sa.Column('estimated_monthly_waste', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_cloud_account_id'), 'scans', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('orphan_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('cloud_account_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('estimated_monthly_cost', sa.Float(), nullable=False),
    sa.Column('resource_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orphan_resources_cloud_account_id'), 'orphan_resources', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_orphan_resources_id'), 'orphan_resources', ['id'], unique=False)
    op.create_index(op.f('ix_orphan_resources_region'), 'orphan_resources', ['region'], unique=False)
    op.create_index(op.f('ix_orphan_resources_resource_id'), 'orphan_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_orphan_resources_resource_type'), 'orphan_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_orphan_resources_scan_id'), 'orphan_resources', ['scan_id'], unique=False)
    op.create_index(op.f('ix_orphan_resources_status'), 'orphan_resources', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orphan_resources_status'), table_name='orphan_resources')
    op.drop_index(op.f('ix_orphan_resources_scan_id'), table_name='orphan_resources')
    op.drop_index(op.f('ix_orphan_resources_resource_type'), table_name='orphan_resources')
    op.drop_index(op.f('ix_orphan_resources_resource_id'), table_name='orphan_resources')
    op.drop_index(op.f('ix_orphan_resources_region'), table_name='orphan_resources')
    op.drop_index(op.f('ix_orphan_resources_id'), table_name='orphan_resources')
    op.drop_index(op.f('ix_orphan_resources_cloud_account_id'), table_name='orphan_resources')
    op.drop_table('orphan_resources')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_cloud_account_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
